import {
	readFileSync,
	writeFileSync,
	existsSync,
	cpSync,
	readdirSync,
	rmSync
} from 'node:fs';
import { resolve } from 'node:path';
import type { Plugin } from 'vite';

const GUIDE_FOR_FRONTEND = `
<!--
  This is a static build of the frontend.
  It is automatically generated by the build process.
  Do not edit this file directly.
  To make changes, refer to the "Web UI" section in the README.
-->
`.trim();

function normalizeEnv(root: string) {
	const envPath = resolve(root, '_app/env.js');
	if (existsSync(envPath)) {
		let content = readFileSync(envPath, 'utf-8');
		content = content.replace(/__sveltekit_[a-z0-9]+/g, '__sveltekit__');
		writeFileSync(envPath, content, 'utf-8');
		console.log('✓ Normalized env.js');
	}
}

function postprocessHtml(root: string) {
	const indexPath = resolve(root, 'index.html');
	if (!existsSync(indexPath)) return;

	let content = readFileSync(indexPath, 'utf-8');

	// Inline favicon as base64
	const faviconPath = resolve('static/favicon.svg');
	if (existsSync(faviconPath)) {
		const faviconContent = readFileSync(faviconPath, 'utf-8');
		const faviconBase64 = Buffer.from(faviconContent).toString('base64');
		const faviconDataUrl = `data:image/svg+xml;base64,${faviconBase64}`;
		content = content.replace(/href="[^"]*favicon\.svg"/g, `href="${faviconDataUrl}"`);
		console.log('✓ Inlined favicon.svg as base64 data URL');
	}

	content = content.replace(/\r/g, '');
	content = GUIDE_FOR_FRONTEND + '\n' + content;

	// Ensure all paths are relative (svelte.config.js has paths.relative: true)
	// but this is a safety net for any remaining absolute paths (attributes + inline scripts)
	content = content.replace(/="\/_app\//g, '="./_app/');
	content = content.replace(/import\("\/_app\//g, 'import("./_app/');
	content = content.replace(/href="\/favicon/g, 'href="./favicon');

	writeFileSync(indexPath, content, 'utf-8');
	console.log('✓ Updated index.html');
}

export function llamaCppBuildPlugin(): Plugin {
	return {
		name: 'llamacpp:build',
		apply: 'build',
		closeBundle() {
			setTimeout(() => {
				try {
					const distRoot = resolve('dist');
					const pubRoot = resolve('../public');

					// Process dist/ output (normalize + postprocess)
					normalizeEnv(distRoot);
					postprocessHtml(distRoot);

					// Only copy to ../public if it exists (local llama.cpp server build)
					if (existsSync(pubRoot)) {
						// Clean generated files in public/
						for (const f of readdirSync(pubRoot)) {
							if (f === '_app' || f === 'bundle.js' || f === 'bundle.css') {
								rmSync(resolve(pubRoot, f), { recursive: true, force: true });
							}
						}

						// Copy dist/_app/* → public/_app/*
						cpSync(resolve(distRoot, '_app'), resolve(pubRoot, '_app'), { recursive: true });

						// Copy fallback index.html
						cpSync(resolve(distRoot, 'index.html'), resolve(pubRoot, 'index.html'));

						normalizeEnv(pubRoot);
						postprocessHtml(pubRoot);
					}
				} catch (error) {
					console.error('Failed to post-process build:', error);
				}
			}, 100);
		}
	};
}
